// <auto-generated />
using CS_Ogretici.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS_Ogretici.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230503000905_deneme")]
    partial class deneme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS_Ogretici.Models.Basliklar", b =>
                {
                    b.Property<int>("BaslikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaslikId"));

                    b.Property<string>("BaslikAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaslikParentId")
                        .HasColumnType("int");

                    b.Property<string>("BaslikYol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BaslikId");

                    b.ToTable("Basliklars");
                });

            modelBuilder.Entity("CS_Ogretici.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAd")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("KullaniciEposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSoyad")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilars");
                });
#pragma warning restore 612, 618
        }
    }
}
